### ISSUE TITLE
请问 nanopi-r2_linux_defconfig 是应该用这个库里的还是 kernel 的库里的

### ISSUE THREAD

**Issue by songchenwen** [fanck0605/friendlywrt-nanopi_r2s#3]
请问 `nanopi-r2_linux_defconfig` 是应该用这个库里的还是 kernel 的库里的？您对这两个库的定位是什么样的？是先用这个库的 `nanopi-r2_linux_defconfig` 做试验，稳定后同步到 kernel 的库里吗？

**Comment by fanck0605** [comment]
你先用我这个库里的吧。
这个库里的 `nanopi-r2_linux_defconfig` 主要是基于 friendlywrt-kernel 里的 `nanopi-r2_linux_defconfig` 继续合并了 [target/linux/generic/config-4.14](https://github.com/coolsnowwolf/lede/blob/master/target/linux/generic/config-4.14) 的配置，更加全面一点吧。
我简单测试了一下，来这么配置 kernel 已经不会导致 防火墙 崩溃 的问题了。
friendlywrt-kernel 里面的没做啥大的修改，
我打算再测试一下，没啥大问题了再同步到 friendlywrt-kernel 里。

**Comment by songchenwen** [comment]
嗯，我用的这个库里的 kernel config 已经好几天没有遇到过 firewall 崩溃了。我看你现在已经不用这个库里的 kernel config 了。所以有点困惑，这两个库的 kernel config 是会先改哪一个再同步到另一个，还是一个别的什么流程？

**Comment by songchenwen** [comment]
是不是这样一个流程更合适一些？此库的 kernel config 作为新改动的测试方式。[friendlywrt-kernel](https://github.com/fanck0605/friendlywrt-kernel) 这个库里的作为测试稳定后的 config。这样 [friendlywrt-kernel](https://github.com/fanck0605/friendlywrt-kernel) 这个库实际上就可以直接提供给别的项目用了。

**Comment by fanck0605** [comment]
对的

**Comment by songchenwen** [comment]
后续 [friendlywrt-kernel](https://github.com/fanck0605/friendlywrt-kernel) 可以用 GitHub Actions 做自动 Merge Upstream，这样大部分情况下你也不需要管它了。

**Comment by fanck0605** [comment]
这个的话，我打算有空了再给他写个脚本自动 merge

**Comment by songchenwen** [comment]
我[在这](https://github.com/songchenwen/openwrt-package/blob/master/.github/workflows/merge_upstream.yml) 写过一个自动merge 的脚本，你可以看看

**Comment by fanck0605** [comment]
你可以试一下一次性添加多条防火墙转发配置，我这边还有概率死防火墙，越来越感觉是 lean 的 openwrt 的问题了。

**Comment by songchenwen** [comment]
按你说的试了，确实还是会有概率死防火墙

**Comment by fanck0605** [comment]
我也写了个脚本来守护防火墙，目前没啥好办法了，需要安装 **jq** 用于获取 IP 地址
https://github.com/fanck0605/nanopi-r2s/blob/lean/scripts/check_net4.sh

**Comment by fanck0605** [comment]
目前内核配置，防火墙同时添加多条记录也不会崩了。
两仓库内，内核配置已同步
