### ISSUE TITLE
请问您的lean’s openwrt还在维护更新吗？

### ISSUE THREAD

**Issue by Benjamin23333** [fanck0605/friendlywrt-nanopi_r2s#9]
我看到您的action下的lean’ openwrt没有更新，之前都是每天两点开始编译，今天两点没有开始编译，而只有lienol’s openwrt，请问您是放弃lean’ openwrt而全面转向lienol’s openwrt了吗？

**Comment by fanck0605** [comment]
又没有啥问题，没啥好更新的呀。就每天编译一下上游最新的源码。

**Comment by Benjamin23333** [comment]
> 又没有啥问题，没啥好更新的呀。就每天编译一下上游最新的源码。

这样啊，我看到突然没新编译还以为放弃了呢😂，那另外我想问一下，可以添加passwall吗？如果有什么麻烦的，就不必了

**Comment by fanck0605** [comment]
@Benjamin23333
这个友善的 SDK 太混乱了，最近比较忙，以后也可能不更新了
可以看一下我维护的这个项目 [openwrt-nanopi-r2s](https://github.com/fanck0605/openwrt-nanopi-r2s)
或者可以看看 QiuSimons 大佬的固件 [R2S-OpenWrt](https://github.com/project-openwrt/R2S-OpenWrt)
